# Generated by Django 5.0 on 2023-12-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=50)),
                ('location', models.TextField(max_length=50)),
                ('about', models.TextField(max_length=250)),
                ('type', models.CharField(choices=[('IT', 'IT'), ('Non-IT', 'Non-IT'), ('NGOs', 'NGOs'), ('INGOs', 'INGOs')], max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('added_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
