# Generated by Django 5.0 on 2023-12-12 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=50)),
                ('positions', models.CharField(choices=[('manager', 'manager'), ('board-member', 'board-member'), ('software-engineer', 'software-engineer'), ('other', 'other')], max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company')),
            ],
        ),
    ]
